---
- hosts: proxmox
  tasks:
  - name: My first task
    community.general.proxmox:
      validate_certs: false
      node: "{{ CT_NAME }}"
      api_user: "{{ API_USER }}"
      api_password: "{{ PVE_PASS}}"
      api_host: bart
      password: "{{ CT_PASS }}"
      hostname: "{{ CT_HOSTNAME }}"
      ostemplate: local:var/lib/vz/template/cache/debian-12-standard_12.2-1_amd64.tar.zst
      netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"}'
